/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-cs330_project2023
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_CS330_PROJECT2023_API_H
#define INCLUDED_CS330_PROJECT2023_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_cs330_project2023_EXPORTS
#define CS330_PROJECT2023_API __GR_ATTR_EXPORT
#else
#define CS330_PROJECT2023_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_CS330_PROJECT2023_API_H */
