/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(constellation_mapping_4569.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c6d33b2df0e68d4b68c68295982d7f42)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/chris_module/constellation_mapping_4569.h>
// pydoc.h is automatically generated in the build directory
#include <constellation_mapping_4569_pydoc.h>

void bind_constellation_mapping_4569(py::module& m)
{

    using constellation_mapping_4569    = gr::chris_module::constellation_mapping_4569;


    py::class_<constellation_mapping_4569, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<constellation_mapping_4569>>(m, "constellation_mapping_4569", D(constellation_mapping_4569))

        .def(py::init(&constellation_mapping_4569::make),
           D(constellation_mapping_4569,make)
        )
        



        ;




}








