/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lab1_block.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3e15def3b04e8bb1f340a87e088d21ae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lab1_module/lab1_block.h>
// pydoc.h is automatically generated in the build directory
#include <lab1_block_pydoc.h>

void bind_lab1_block(py::module& m)
{

    using lab1_block    = gr::lab1_module::lab1_block;


    py::class_<lab1_block, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<lab1_block>>(m, "lab1_block", D(lab1_block))

        .def(py::init(&lab1_block::make),
           D(lab1_block,make)
        )
        



        ;




}








