/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fec_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d40fed99be1e3dfc9c8b52eb6c7c97ce)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cs330_project2023/fec_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <fec_decoder_pydoc.h>

void bind_fec_decoder(py::module& m)
{

    using fec_decoder    = gr::cs330_project2023::fec_decoder;


    py::class_<fec_decoder, gr::block, gr::basic_block,
        std::shared_ptr<fec_decoder>>(m, "fec_decoder", D(fec_decoder))

        .def(py::init(&fec_decoder::make),
           D(fec_decoder,make)
        )
        



        ;




}








