/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fec_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0951a4618788b3ad4c212e5388c597bf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cs330_project2023/fec_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <fec_encoder_pydoc.h>

void bind_fec_encoder(py::module& m)
{

    using fec_encoder    = gr::cs330_project2023::fec_encoder;


    py::class_<fec_encoder, gr::block, gr::basic_block,
        std::shared_ptr<fec_encoder>>(m, "fec_encoder", D(fec_encoder))

        .def(py::init(&fec_encoder::make),
           D(fec_encoder,make)
        )
        



        ;




}








